-- =============================================
-- TrendTracker ID - Migration 004
-- Caption history and usage tracking tables.
-- =============================================

-- ----------------------------
-- 1. caption_history
-- Logs every caption generated by a user for a product.
-- ----------------------------
CREATE TABLE caption_history (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE caption_history IS
  'Tracks which user generated a caption for which product.';

ALTER TABLE caption_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own caption history"
  ON caption_history
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own caption history"
  ON caption_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ----------------------------
-- 2. caption_usage
-- Daily usage counter per user (free tier = 3/day).
-- Unique constraint prevents duplicate rows per user per day.
-- ----------------------------
CREATE TABLE caption_usage (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  count      int  NOT NULL DEFAULT 1,

  UNIQUE (user_id, usage_date)
);

COMMENT ON TABLE caption_usage IS
  'Daily caption usage counter per user. UNIQUE(user_id, usage_date) enables simple upsert.';

ALTER TABLE caption_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own usage"
  ON caption_usage
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can upsert their own usage"
  ON caption_usage
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own usage"
  ON caption_usage
  FOR UPDATE
  USING (auth.uid() = user_id);